name: xeus-sqlite
channels:
  - conda-forge
dependencies:
  # Builde dependencies
  - cmake
  # host dependencies
  - nlohmann_json
  - xtl
  - cppzmq
  - xeus
  - xeus-zmq=1.1.1
  - sqlite
  - sqlitecpp
  - cpp-tabulate=1.5
  - xvega=0.0.10
  - xproperty=0.11.0
  - xvega-bindings=0.0.10
  # Test dependencies
  - pytest
  - jupyter_kernel_test
