name: xeus-sqlite
channels:
  - conda-forge
dependencies:
  # Builde dependencies
  - cmake
  # host dependencies
  - nlohmann_json
  - xtl=0.7.2
  - cppzmq
  - xeus=2.0.0
  - sqlite
  - sqlitecpp
  - cpp-tabulate=1.3
  - xvega=0.0.10
  - xproperty=0.11.0
  - xvega-bindings=0.0.10
  # Test dependencies
  - pytest
  - jupyter_kernel_test
