name: xeus-sqlite
channels:
  - conda-forge
dependencies:
  # Build dependencies
  - cmake
  - cxx-compiler
  # Host dependencies
  - nlohmann_json
  - cppzmq
  - xeus>=5.0.0,<=6.0
  - xeus-zmq
  - sqlite
  - sqlitecpp
  - cpp-tabulate=1.5
  - xvega=0.0.10
  - xproperty>=0.12.0
  - xvega-bindings=0.0.10
  # Test dependencies
  - pytest
  - jupyter_kernel_test
