name: xeus-sqlite
channels:
  - conda-forge
dependencies:
  # Build dependencies
  - cmake
  - gcc_linux-64=7.5.0
  - gcc_impl_linux-64=7.5.0
  - gxx_linux-64=7.5.0
  - gxx_impl_linux-64=7.5.0
  # Host dependencies
  - nlohmann_json
  - xtl
  - cppzmq
  - xeus-zmq=1.1.1
  - sqlite
  - sqlitecpp
  - cpp-tabulate=1.5
  - xvega=0.0.10
  - xproperty=0.11.0
  - xvega-bindings=0.0.10
  # Test dependencies
  - pytest
  - jupyter_kernel_test
