name: xeus-sqlite
channels:
  - conda-forge
dependencies:
  # Builde dependencies
  - cmake
  # host dependencies
  - nlohmann_json
  - xtl
  - cppzmq
  - xeus
  - sqlite
  - sqlitecpp
  - cpp-tabulate=1.3
  - xvega
  - xproperty
  - xvega-bindings
  # Test dependencies
  - pytest
  - jupyter_kernel_test
