name: xeus-sqlite
channels:
  - conda-forge
dependencies:
  # Build dependencies
  - cmake
  - cxx-compiler
  # Host dependencies
  - nlohmann_json
  - xeus-zmq>=3.0.0,<=4.0
  - sqlite
  - sqlitecpp
  - cpp-tabulate=1.5
  - xvega>=0.1.0
  - xproperty>=0.12.0
  - xvega-bindings>=0.1.0
  # Test dependencies
  - pytest
  - jupyter_kernel_test
